# Site settings
title: jbeane.github.io
email: joe.beane18@gmail.com
description: > 
    I'm a web developer: html css js jquery php and more! - bunny dad: don't talk bad about bunnies. - computer hardware enthusiast: because intel and nvidia. - vegan: because life.
baseurl: ""
url: "http://jbeane.github.io"
github_username:  jbeane

# Build settings
markdown: kramdown
