# Site settings
title: jbeane.github.io
email: joe.beane18@gmail.com
description: > 
    I'm a web developer - bunny lover - animal rights activist - gamer - guy - etc - you get the point 
baseurl: ""
url: "http://jbeane.github.io"
twitter_username: BeaneBunny
github_username:  jbeane

# Build settings
markdown: kramdown
