# Site settings
title: jbeane.github.io
email: joe.beane18@gmail.com
description: > 
    I'm a web developer: html css js jquery php and more! The idea to keep this site up to date with different things I am forcing myself to learn.
baseurl: ""
url: "http://jbeane.github.io"
github_username:  jbeane

# Build settings
markdown: kramdown
